[package]
name = 'kana-aggregator'
version = '0.0.1'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'e5d11a7830f452133281e36ddd79396ae7590d39'

[addresses]
kana_aggregator = "0x82f3888ab2a8e76e67cf24a2ecffe3205f463f3a92b0d36d3910f3f5ece51121"