[package]
name = 'kana-aggregator'
version = '1.0.0'
[dependencies]
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "71cc8c83b85c54702adce6c32d4063f2acced00f" }
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'v0.3.0'
[dependencies.TestCoins]
git = 'https://github.com/pontem-network/test-coins.git'
rev = 'v0.1.0'
[addresses]
kana_aggregator = "0x82b94c0423cf25f6a58589f992390ec917eec0945198d9031c10cd79cedb6699"
pontem = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
liquid_swap = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"