[package]
name = 'kana-aggregator'
version = '0.0.1'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'e5d11a7830f452133281e36ddd79396ae7590d39'

[dependencies]
Aptoswap = { local = "./interface/aptoswap" }

[addresses]
kana_aggregator = "0x2fd573969cf2d5f0bf8bc9ec245dec6d031f6e00e50f32785913135c318a2dcd"
