[package]
name = 'kana-aggregator'
version = '1.0.0'
[dependencies]
basiq = { local = "./interface/basiq-basiq" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
LiquidswapLP = { local = "./interface/pontem-LiquidswapLP" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "71cc8c83b85c54702adce6c32d4063f2acced00f" }
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
kana_aggregator = "0x82b94c0423cf25f6a58589f992390ec917eec0945198d9031c10cd79cedb6699"
user="0x2"
